In [15]:
def load_and_reindex(path,filelist):
    start_time = datetime.now()
    df = None
    for file in filelist:
        year = file[-8:-4]
        manager = file.split('_')[0]
        if df is None:
            df = pd.read_csv(path+file)
            df['year'] = str(int(year) -1)
            df.index = manager+'_'+year+'_'+df.index.astype(str)
        else:
            temp = pd.read_csv(path+file)
            temp['year'] = str(int(year) -1) 
            temp.index = manager+'_'+year+'_'+temp.index.astype(str)
            df = df.append(temp)
    #for i in df['annual_consume']:
        #if
    df['low_tarif_consumption'] = df['annual_consume'].multiply(df['annual_consume_lowtarif_perc']/100)
    try:
        df['num_active_connections'] = df['num_connections'].multiply(df['perc_of_active_connections']/100).astype(int)
    except ValueError:
        df['num_active_connections'] = df['num_connections'].multiply(df['perc_of_active_connections']/100)
    try:
        df['num_smartmeters'] = df['num_connections'].multiply(df['smartmeter_perc']/100).astype(int)
    except ValueError:
        df['num_smartmeters'] = df['num_connections'].multiply(df['smartmeter_perc']/100)
        #print('Number of smartmeters could not be calculated')
    df['net_annual_consumption'] = df['annual_consume'].multiply(df['delivery_perc']/100)
    df['self_production'] = df['annual_consume'] - df['net_annual_consumption']
    df['self_prod_perc'] = df['self_production'].divide(df['annual_consume']/100)
    
    time_elapsed = datetime.now() - start_time
    print('Made main dataframe, time elapsed (hh:mm:ss.ms) {}'.format(time_elapsed))
    return(df)

import numpy as np 
import pandas as pd 
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.cm
from matplotlib import gridspec
import matplotlib as mpl
import seaborn as sns
 


import os

In [16]:
path = "C:/Users/vlad/Downloads/Data Science-20210518T081033Z-001/Data Science/Electricity/"
files_all = [f for f in os.listdir(path)]
elec_all = load_and_reindex(path,files_all)

Made main dataframe, time elapsed (hh:mm:ss.ms) 0:01:40.699984

In [63]:
elec_all

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,...,STANDAARDDEVIATIE,%Defintieve aansl (NRM),low_tarif_consumption,num_active_connections,num_smartmeters,net_annual_consumption,self_production,self_prod_perc,zipcode_from_int,provider
coteq_2019_0,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,Dorpsstraat,7468CP,7471AA,ENTER,19.0,89.47,94.74,89.0,...,NaN,NaN,3611.9039,18.0006,0.0,3611.9039,425.0961,10.53,7468,coteq
coteq_2019_1,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AB,7471AB,GOOR,40.0,100.00,97.50,80.0,...,NaN,NaN,2509.9000,39.0000,0.0,2642.0000,0.0000,0.00,7471,coteq
coteq_2019_2,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AC,7471AC,GOOR,16.0,100.00,100.00,100.0,...,NaN,NaN,1313.0000,16.0000,0.0,1313.0000,0.0000,0.00,7471,coteq
coteq_2019_3,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AD,7471AE,GOOR,41.0,92.68,85.37,54.0,...,NaN,NaN,5936.1540,35.0017,0.0,5936.1540,468.8460,7.32,7471,coteq
coteq_2019_4,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,Kerkstraat,7471AG,7471AG,GOOR,14.0,85.71,100.00,36.0,...,NaN,NaN,4742.0000,14.0000,0.0,4064.3682,677.6318,14.29,7471,coteq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
westland-infra_2019_2319,westland-infra,871687800090000015,IN DE BALIJE,3155XA,3155XA,MAASLAND,14.0,100.00,100.00,100,...,NaN,100.0,6065.0000,14.0000,0.0,6065.0000,0.0000,0.00,3155,westland-infra
westland-infra_2019_2320,westland-infra,871687800090000015,KONINGIN JULIANAWEG,3155XB,3155XB,MAASLAND,14.0,100.00,100.00,86,...,NaN,100.0,4356.9912,14.0000,0.0,4692.0000,0.0000,0.00,3155,westland-infra
westland-infra_2019_2321,westland-infra,871687800090000015,KONINGIN JULIANAWEG,3155XC,3155XD,MAASLAND,29.0,89.66,100.00,86,...,NaN,100.0,5335.5369,29.0000,0.0,5549.0574,639.9426,10.34,3155,westland-infra
westland-infra_2019_2322,westland-infra,871687800090000015,KONINGIN JULIANAWEG,3155XE,3155XH,MAASLAND,28.0,100.00,100.00,100,...,NaN,100.0,4309.0000,28.0000,0.0,4309.0000,0.0000,0.00,3155,westland-infra
westland-infra_2019_2323,westland-infra,871687800090000015,MERESTEIJN,3155XJ,3155XK,MAASLAND,19.0,89.47,100.00,95,...,NaN,100.0,6320.0000,19.0000,0.0,5654.5040,665.4960,10.53,3155,westland-infra

In [17]:
elec_all = elec_all.dropna(subset=['zipcode_from','zipcode_to'])
elec_all['zipcode_from_int'] = elec_all['zipcode_from'].str[:-2].astype(int)
sumcols = ['annual_consume','num_connections','low_tarif_consumption','num_smartmeters','net_annual_consumption','self_production']
meancols = ['annual_consume_lowtarif_perc','delivery_perc','perc_of_active_connections','smartmeter_perc','self_prod_perc']
elec_all['provider'] = [f[0] for f in elec_all.index.str.split('_')]

postalcode_geoloc = pd.read_csv('C:/Users/vlad/Downloads/Data Science-20210518T081033Z-001/Data Science/4pp.csv').set_index('postcode',drop=False)

import geopandas as gpd
import geopandas
from matplotlib.patches import Patch

def make_group_zipcode(df):
    c_df = pd.DataFrame()
    i =2009
    while i < 2020:
        df2 = df[df.year==str(i)]
        pc_df = df2.groupby('zipcode_from_int').sum()[sumcols]#.count()['city']
        pc_df = pc_df.join(df.groupby('zipcode_from_int').mean()[meancols])
        pc_df = pc_df.join(df.groupby('zipcode_from_int').count()['city']).rename({'city':'code_count'},axis=1)
        pc_df = pc_df.join(df.groupby('zipcode_from_int').first()[['city','provider']])
        values = [str(i)+'_'+f for f in pc_df.columns]
        pc_df.rename(dict(zip(pc_df.columns,values)),axis=1,inplace=True)
        c_df = pd.concat([c_df, pc_df])
        i=int(i+1)
    c_df = c_df.join(postalcode_geoloc,how='left') #add geolocation
    return c_df

In [45]:
pc_2018 = make_group_zipcode(elec_all)
pc_2019 = make_group_zipcode(elec_all)

In [59]:
pc_2018['postcode'].nunique()

4047

In [48]:
pc_2019['2018_annual_consume'].sum()

53581318796.0

In [70]:
pc_2018.dropna(subset=['provincie'])
pc_2018 = pc_2018.groupby('provincie').sum().reset_index()
pc_2019.dropna(subset=['gemeente'])
pc_2019 = pc_2019.groupby('gemeente').sum().reset_index()

In [71]:
import json
counties = json.load(open('C:/Users/vlad/Downloads/Data Science-20210518T081033Z-001/Data Science/Geo/provinces.GEOJSON','r'))
len(counties['features'])
counties2 = json.load(open('C:/Users/vlad/Downloads/Data Science-20210518T081033Z-001/Data Science/Geo/townships.GEOJSON','r'))
len(counties2['features'])

394

In [72]:
state_id_map = {}
state_id_map2 = {}
for feature in counties['features']:
    feature['id'] = feature['properties']['regioFacetId']
    state_id_map[feature['properties']['name']] = feature['id']
for feature in counties2['features']:
    feature['id'] = feature['properties']['regioFacet']
    state_id_map2[feature['properties']['name']] = feature['id']
sorted(state_id_map2.keys())

["'s-Gravenhage",
 "'s-Hertogenbosch",
 'Aa en Hunze',
 'Aalburg',
 'Aalsmeer',
 'Aalten',
 'Achtkarspelen',
 'Alblasserdam',
 'Albrandswaard',
 'Alkmaar',
 'Almelo',
 'Almere',
 'Alphen aan den Rijn',
 'Alphen-Chaam',
 'Ameland',
 'Amersfoort',
 'Amstelveen',
 'Amsterdam',
 'Apeldoorn',
 'Appingedam',
 'Arnhem',
 'Assen',
 'Asten',
 'Baarle-Nassau',
 'Baarn',
 'Barendrecht',
 'Barneveld',
 'Bedum',
 'Beek',
 'Beemster',
 'Beesel',
 'Bellingwedde',
 'Bergeijk',
 'Bergen (L)',
 'Bergen (NH)',
 'Bergen op Zoom',
 'Berkelland',
 'Bernheze',
 'Best',
 'Beuningen',
 'Beverwijk',
 'Binnenmaas',
 'Bladel',
 'Blaricum',
 'Bloemendaal',
 'Bodegraven-Reeuwijk',
 'Boekel',
 'Borger-Odoorn',
 'Borne',
 'Borsele',
 'Boxmeer',
 'Boxtel',
 'Breda',
 'Brielle',
 'Bronckhorst',
 'Brummen',
 'Brunssum',
 'Bunnik',
 'Bunschoten',
 'Buren',
 'Bussum',
 'Capelle aan den IJssel',
 'Castricum',
 'Coevorden',
 'Cranendonck',
 'Cromstrijen',
 'Cuijk',
 'Culemborg',
 'Dalfsen',
 'Dantumadeel (Dantumadiel)',
 'De Bilt',
 'De Friese Meren',
 'De Marne',
 'De Ronde Venen',
 'De Wolden',
 'Delft',
 'Delfzijl',
 'Den Helder',
 'Deurne',
 'Deventer',
 'Diemen',
 'Dinkelland',
 'Doesburg',
 'Doetinchem',
 'Dongen',
 'Dongeradeel',
 'Dordrecht',
 'Drechterland',
 'Drimmelen',
 'Dronten',
 'Druten',
 'Duiven',
 'Echt-Susteren',
 'Edam-Volendam',
 'Ede',
 'Eemnes',
 'Eemsmond',
 'Eersel',
 'Eijsden-Margraten',
 'Eindhoven',
 'Elburg',
 'Emmen',
 'Enkhuizen',
 'Enschede',
 'Epe',
 'Ermelo',
 'Etten-Leur',
 'Ferwerderadeel (Ferwerderadiel)',
 'Franekeradeel',
 'Geertruidenberg',
 'Geldermalsen',
 'Geldrop-Mierlo',
 'Gemert-Bakel',
 'Gennep',
 'Giessenlanden',
 'Gilze en Rijen',
 'Goeree-Overflakkee',
 'Goes',
 'Goirle',
 'Gorinchem',
 'Gouda',
 'Grave',
 'Groesbeek',
 'Groningen (Gr)',
 'Grootegast',
 'Gulpen-Wittem',
 'Haaksbergen',
 'Haaren',
 'Haarlem',
 'Haarlemmerliede en Spaarnwoude',
 'Haarlemmermeer',
 'Halderberge',
 'Hardenberg',
 'Harderwijk',
 'Hardinxveld-Giessendam',
 'Haren',
 'Harlingen',
 'Hattem',
 'Heemskerk',
 'Heemstede',
 'Heerde',
 'Heerenveen',
 'Heerhugowaard',
 'Heerlen',
 'Heeze-Leende',
 'Heiloo',
 'Hellendoorn',
 'Hellevoetsluis',
 'Helmond',
 'Hendrik-Ido-Ambacht',
 'Hengelo (O)',
 'Heumen',
 'Heusden',
 'Hillegom',
 'Hilvarenbeek',
 'Hilversum',
 'Hof van Twente',
 'Hollands Kroon',
 'Hoogeveen',
 'Hoogezand-Sappemeer',
 'Hoorn',
 'Horst aan de Maas',
 'Houten',
 'Huizen',
 'Hulst',
 'IJsselstein',
 'Kaag en Braassem',
 'Kampen',
 'Kapelle',
 'Katwijk',
 'Kerkrade',
 'Koggenland',
 'Kollumerland en Nieuwkruisland',
 'Korendijk',
 'Krimpen aan den IJssel',
 'Krimpenerwaard',
 'Laarbeek',
 'Landerd',
 'Landgraaf',
 'Landsmeer',
 'Langedijk',
 'Lansingerland',
 'Laren',
 'Leek',
 'Leerdam',
 'Leeuwarden',
 'Leeuwarderadeel',
 'Leiden',
 'Leiderdorp',
 'Leidschendam-Voorburg',
 'Lelystad',
 'Leudal',
 'Leusden',
 'Lingewaal',
 'Lingewaard',
 'Lisse',
 'Littenseradeel (Littenseradiel)',
 'Lochem',
 'Loon op Zand',
 'Lopik',
 'Loppersum',
 'Losser',
 'Maasdonk',
 'Maasdriel',
 'Maasgouw',
 'Maassluis',
 'Maastricht',
 'Marum',
 'Medemblik',
 'Meerssen',
 'Menaldumadeel (Menaldumadiel)',
 'Menterwolde',
 'Meppel',
 'Middelburg',
 'Midden-Delfland',
 'Midden-Drenthe',
 'Mill en Sint Hubert',
 'Moerdijk',
 'Molenwaard',
 'Montferland',
 'Montfoort',
 'Mook en Middelaar',
 'Muiden',
 'Naarden',
 'Neder-Betuwe',
 'Nederweert',
 'Neerijnen',
 'Nieuwegein',
 'Nieuwkoop',
 'Nijkerk',
 'Nijmegen',
 'Nissewaard',
 'Noord-Beveland',
 'Noordenveld',
 'Noordoostpolder',
 'Noordwijk',
 'Noordwijkerhout',
 'Nuenen, Gerwen en Nederwetten',
 'Nunspeet',
 'Nuth',
 'Oegstgeest',
 'Oirschot',
 'Oisterwijk',
 'Oldambt',
 'Oldebroek',
 'Oldenzaal',
 'Olst-Wijhe',
 'Ommen',
 'Onderbanken',
 'Oost Gelre',
 'Oosterhout',
 'Ooststellingwerf',
 'Oostzaan',
 'Opmeer',
 'Opsterland',
 'Oss',
 'Oud-Beijerland',
 'Oude IJsselstreek',
 'Ouder-Amstel',
 'Oudewater',
 'Overbetuwe',
 'Papendrecht',
 'Peel en Maas',
 'Pekela',
 'Pijnacker-Nootdorp',
 'Purmerend',
 'Putten',
 'Raalte',
 'Reimerswaal',
 'Renkum',
 'Renswoude',
 'Reusel-De Mierden',
 'Rheden',
 'Rhenen',
 'Ridderkerk',
 'Rijnwaarden',
 'Rijssen-Holten',
 'Rijswijk',
 'Roerdalen',
 'Roermond',
 'Roosendaal',
 'Rotterdam',
 'Rozendaal',
 'Rucphen',
 'Schagen',
 'Scherpenzeel',
 'Schiedam',
 'Schiermonnikoog',
 'Schijndel',
 'Schinnen',
 'Schouwen-Duiveland',
 'Simpelveld',
 'Sint Anthonis',
 'Sint-Michielsgestel',
 'Sint-Oedenrode',
 'Sittard-Geleen',
 'Sliedrecht',
 'Slochteren',
 'Sluis',
 'Smallingerland',
 'Soest',
 'Someren',
 'Son en Breugel',
 'Stadskanaal',
 'Staphorst',
 'Stede Broec',
 'Steenbergen',
 'Steenwijkerland',
 'Stein',
 'Stichtse Vecht',
 'Strijen',
 'SÃºdwest-FryslÃ¢n',
 'Ten Boer',
 'Terneuzen',
 'Terschelling',
 'Texel',
 'Teylingen',
 'Tholen',
 'Tiel',
 'Tietjerksteradeel (Tytsjerksteradiel)',
 'Tilburg',
 'Tubbergen',
 'Twenterand',
 'Tynaarlo',
 'Uden',
 'Uitgeest',
 'Uithoorn',
 'Urk',
 'Utrecht (Ut)',
 'Utrechtse Heuvelrug',
 'Vaals',
 'Valkenburg aan de Geul',
 'Valkenswaard',
 'Veendam',
 'Veenendaal',
 'Veere',
 'Veghel',
 'Veldhoven',
 'Velsen',
 'Venlo',
 'Venray',
 'Vianen',
 'Vlaardingen',
 'Vlagtwedde',
 'Vlieland',
 'Vlissingen',
 'Voerendaal',
 'Voorschoten',
 'Voorst',
 'Vught',
 'Waalre',
 'Waalwijk',
 'Waddinxveen',
 'Wageningen',
 'Wassenaar',
 'Waterland',
 'Weert',
 'Weesp',
 'Werkendam',
 'West Maas en Waal',
 'Westerveld',
 'Westervoort',
 'Westland',
 'Weststellingwerf',
 'Westvoorne',
 'Wierden',
 'Wijchen',
 'Wijdemeren',
 'Wijk bij Duurstede',
 'Winsum',
 'Winterswijk',
 'Woensdrecht',
 'Woerden',
 'Wormerland',
 'Woudenberg',
 'Woudrichem',
 'Zaanstad',
 'Zaltbommel',
 'Zandvoort',
 'Zederik',
 'Zeevang',
 'Zeewolde',
 'Zeist',
 'Zevenaar',
 'Zoetermeer',
 'Zoeterwoude',
 'Zuidhorn',
 'Zuidplas',
 'Zundert',
 'Zutphen',
 'Zwartewaterland',
 'Zwijndrecht',
 'Zwolle',
 'het Bildt']

In [73]:
pc_2019

,gemeente,2009_annual_consume,2009_num_connections,2009_low_tarif_consumption,2009_num_smartmeters,2009_net_annual_consumption,2009_self_production,2009_annual_consume_lowtarif_perc,2009_delivery_perc,2009_perc_of_active_connections,...,2019_delivery_perc,2019_perc_of_active_connections,2019_smartmeter_perc,2019_self_prod_perc,2019_code_count,id,postcode,netnummer,latitude,longitude
0,'s-Hertogenbosch,12896815.0,62729.0,5.133161e+06,2.9300,1.289355e+07,3260.4800,988.785297,2410.756171,2499.997232,...,2410.756171,2499.997232,1014.168063,89.243829,31886.0,588324.0,1438800.0,20075.0,14220.582803,1465.314912
1,Aa en Hunze,2866964.0,11336.0,1.021293e+06,8.3300,2.865496e+06,1467.7700,1326.421695,2949.584354,3300.000000,...,2850.834354,3200.000000,731.279606,349.165646,6633.0,1562149.0,3382199.0,205626.0,18870.088637,2391.652633
2,Aalburg,1123663.0,3841.0,4.978088e+05,4.0000,1.123663e+06,0.0000,261.546895,577.626944,600.000000,...,577.626944,600.000000,117.671118,22.373056,2053.0,110968.0,281556.0,27456.0,3414.537792,334.267256
3,Aalsmeer,3442853.0,14204.0,1.378107e+06,0.0000,3.438310e+06,4542.7508,125.389347,287.089307,279.648466,...,287.089307,279.648466,41.964985,12.910693,7523.0,8316.0,47256.0,9801.0,1724.461288,157.085766
4,Aalten,3406671.0,12856.0,1.203033e+06,1.9994,3.404859e+06,1812.2108,280.650289,553.981252,563.883531,...,553.981252,563.883531,97.345131,46.018748,7405.0,203874.0,469458.0,30822.0,3426.234100,433.148577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,Zutphen,4669671.0,23635.0,9.417959e+05,180.9987,4.660455e+06,9215.9493,346.180071,860.857866,832.415237,...,860.857866,832.415237,192.007943,39.142134,13099.0,309309.0,713801.0,56925.0,5161.794552,615.174394
427,Zwartewaterland,2167352.0,8414.0,7.794023e+05,4.1100,2.166897e+06,455.3500,254.970943,569.476463,600.000000,...,654.908463,700.000000,216.398811,45.091537,5112.0,260903.0,583984.0,5143.0,3735.162608,429.016415
428,Zwijndrecht,3172763.0,21644.0,2.913018e+06,823.0358,3.158904e+06,13859.4768,639.578475,684.385091,681.222096,...,784.385091,751.222096,223.283060,15.614909,9416.0,93104.0,256286.0,6084.0,4041.952483,360.037682
429,Zwolle,10163459.0,51343.0,3.458294e+06,65.4800,1.016051e+07,2952.9500,901.252797,2234.498141,2400.000000,...,2318.428141,2500.000000,714.810544,181.571859,29277.0,977316.0,2191236.0,10374.0,14337.061495,1666.319636
430,het Bildt,1130488.0,5163.0,3.188431e+05,0.0000,1.128689e+06,1799.3581,263.218622,564.577782,562.195059,...,564.577782,562.195059,81.622420,35.422218,3089.0,273031.0,598752.0,34188.0,3516.368633,372.202829

In [74]:
i = 0
for key in pc_2019['gemeente']:
    if(key in state_id_map2.keys()):
        i=i+1
        print('ok')
    else:
        pc_2019 = pc_2019.drop(index = i)
        i=i+1

ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok

In [75]:
pc_2019.reset_index()

,index,gemeente,2009_annual_consume,2009_num_connections,2009_low_tarif_consumption,2009_num_smartmeters,2009_net_annual_consumption,2009_self_production,2009_annual_consume_lowtarif_perc,2009_delivery_perc,...,2019_delivery_perc,2019_perc_of_active_connections,2019_smartmeter_perc,2019_self_prod_perc,2019_code_count,id,postcode,netnummer,latitude,longitude
0,0,'s-Hertogenbosch,12896815.0,62729.0,5.133161e+06,2.9300,1.289355e+07,3260.4800,988.785297,2410.756171,...,2410.756171,2499.997232,1014.168063,89.243829,31886.0,588324.0,1438800.0,20075.0,14220.582803,1465.314912
1,1,Aa en Hunze,2866964.0,11336.0,1.021293e+06,8.3300,2.865496e+06,1467.7700,1326.421695,2949.584354,...,2850.834354,3200.000000,731.279606,349.165646,6633.0,1562149.0,3382199.0,205626.0,18870.088637,2391.652633
2,2,Aalburg,1123663.0,3841.0,4.978088e+05,4.0000,1.123663e+06,0.0000,261.546895,577.626944,...,577.626944,600.000000,117.671118,22.373056,2053.0,110968.0,281556.0,27456.0,3414.537792,334.267256
3,3,Aalsmeer,3442853.0,14204.0,1.378107e+06,0.0000,3.438310e+06,4542.7508,125.389347,287.089307,...,287.089307,279.648466,41.964985,12.910693,7523.0,8316.0,47256.0,9801.0,1724.461288,157.085766
4,4,Aalten,3406671.0,12856.0,1.203033e+06,1.9994,3.404859e+06,1812.2108,280.650289,553.981252,...,553.981252,563.883531,97.345131,46.018748,7405.0,203874.0,469458.0,30822.0,3426.234100,433.148577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,426,Zutphen,4669671.0,23635.0,9.417959e+05,180.9987,4.660455e+06,9215.9493,346.180071,860.857866,...,860.857866,832.415237,192.007943,39.142134,13099.0,309309.0,713801.0,56925.0,5161.794552,615.174394
368,427,Zwartewaterland,2167352.0,8414.0,7.794023e+05,4.1100,2.166897e+06,455.3500,254.970943,569.476463,...,654.908463,700.000000,216.398811,45.091537,5112.0,260903.0,583984.0,5143.0,3735.162608,429.016415
369,428,Zwijndrecht,3172763.0,21644.0,2.913018e+06,823.0358,3.158904e+06,13859.4768,639.578475,684.385091,...,784.385091,751.222096,223.283060,15.614909,9416.0,93104.0,256286.0,6084.0,4041.952483,360.037682
370,429,Zwolle,10163459.0,51343.0,3.458294e+06,65.4800,1.016051e+07,2952.9500,901.252797,2234.498141,...,2318.428141,2500.000000,714.810544,181.571859,29277.0,977316.0,2191236.0,10374.0,14337.061495,1666.319636
371,430,het Bildt,1130488.0,5163.0,3.188431e+05,0.0000,1.128689e+06,1799.3581,263.218622,564.577782,...,564.577782,562.195059,81.622420,35.422218,3089.0,273031.0,598752.0,34188.0,3516.368633,372.202829

In [76]:
pc_2018['id'] = pc_2018['provincie'].apply(lambda x: state_id_map[x])
pc_2019['id'] = pc_2019['gemeente'].apply(lambda x: state_id_map2[x])

In [77]:
import pandas as pd
import plotly.express as px  # (version 4.7.0)
import plotly.graph_objects as go

import dash  # (version 1.12.0) pip install dash
import dash_core_components as dcc
import dash_html_components as html

from dash.dependencies import Input, Output
app = dash.Dash(__name__)
app.layout = html.Div([

    html.H1("Interactive Dashboard: Electricity consumtion in the Netherlands", style={'text-align': 'center'}),
    dcc.Graph(id='nl_map', figure={}),
    dcc.Dropdown(id="slct_year",
                 options=[
                     {"label": "2009", "value": 2009},
                     {"label": "2010", "value": 2010},
                     {"label": "2011", "value": 2011},
                     {"label": "2012", "value": 2012},
                     {"label": "2013", "value": 2013},
                     {"label": "2014", "value": 2014},
                     {"label": "2015", "value": 2015},
                     {"label": "2016", "value": 2016},
                     {"label": "2017", "value": 2017},
                     {"label": "2018", "value": 2018},
                     {"label": "2019", "value": 2019}],
                 multi=False,
                 value=2015,
                 style={'width': "40%"}
                 ),

    html.Div(id='output_container1', children=[]),
    
    dcc.Dropdown(id="slct_prop",
                 options=[
                     {"label": "Self Production", "value": "_self_production"},
                     {"label": "Percentage of Smartmeters", "value": "_smartmeter_perc"},
                     {"label": "Annual Consumtion", "value": "_annual_consume"},
                     {"label": "Self Production Percentage", "value": "_self_prod_perc"},
                     {"label": "Low tarif Consumtion Percentage", "value": "_annual_consume_lowtarif_perc"}],
                 multi=False,
                 value="_self_production",
                 style={'width': "40%"}
                 ),
    
    html.Br(),
    dcc.Graph(id='ml_map', figure={}),

])


@app.callback(
    [Output(component_id='output_container1', component_property='children'),
     Output(component_id='nl_map', component_property='figure'),
     Output(component_id='ml_map', component_property='figure')],
    [Input(component_id='slct_year', component_property='value'), 
    Input(component_id = 'slct_prop', component_property = 'value')])

def update_graph(option_slctd1,option_slctd2):
    print(option_slctd1)
    print(type(option_slctd1))

    container = "The year chosen by user was: {}".format(option_slctd1)
    
    i = 2018
    dff = pc_2018
    fig = px.choropleth(
        dff,
        locations='id',
        geojson=counties,
        scope = 'europe',
        hover_name='provincie',
        hover_data=[str(option_slctd1)+option_slctd2],
        color=str(option_slctd1)+option_slctd2,
    )
    fig2 = px.choropleth(
        pc_2019,
        locations='id',
        geojson=counties2,
        scope = 'europe',
        hover_name = 'gemeente',
        hover_data=[str(option_slctd1)+option_slctd2],
        color=str(option_slctd1)+option_slctd2,
    )
    fig.update_geos(fitbounds="locations", visible=False)
    fig2.update_geos(fitbounds="locations", visible=False)
    
    return container, fig, fig2

In [ ]:
if __name__ == '__main__':
    app.run_server(debug=True, use_reloader = False, port=8051)

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

Dash is running on http://127.0.0.1:8051/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2015
<class 'int'>
2015
<class 'int'>
2015
<class 'int'>
2015
<class 'int'>
2015
<class 'int'>
2015
<class 'int'>2015
<class 'int'>

2015
<class 'int'>
2016
<class 'int'>
2019
<class 'int'>
2016
<class 'int'>
2016
<class 'int'>
2016
<class 'int'>
2016
<class 'int'>

In [ ]:
%tb